import Head from "next/head";
import { Inter, Roboto_Flex } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto_Flex({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/next.svg" /> {/* Logo on the header */}
      </Head>
      <main>
        <h1 className={roboto.className}>Hello Next JS!</h1>
      </main>
    </>
  );
}
