import Head from "next/head";
import { Inter, Roboto_Flex } from "@next/font/google";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto_Flex({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/next.svg" /> {/* Logo on the header */}
      </Head>

      <main className="text-center bg-white">
        <h1 className={roboto.className}>Hello Next JS!</h1>
        <div className="row">
          <div className="col-3 bg-primary">Col-3</div>
          <div className="col-9 bg-secondary">Col-9</div>
        </div>
      </main>
    </>
  );
}
